---
title: "p-chart"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{p-chart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(shewhart.hybrid)
```

```{r}
#===============================================================================
# Use the example percent positive data by age group to test creating a P chart
# In this example we will create charts for age group, rather than location
# Hence some of the variable names will still refer to place settings rather
# than age group
#===============================================================================


#===============================================================================
# Set up all the library connections we need
#===============================================================================

library(readxl)
library(writexl)
library(utils)
library(httr)
library(DT)
library(tidyverse)
library(broom)
library(readr)
require(dplyr)
library(dplyr)
library(lubridate)
library(googlesheets4)
library(magrittr)
load_all()

#===============================================================================
# Read in the Percent Positive by age group data
#===============================================================================

Pchart_Data <- read_csv("inst/extdata/P Chart Test.csv")

#===============================================================================
# Make sure the date is formatted correctly
#===============================================================================

Pchart_Data$date <- as.Date(Pchart_Data$date, "%m/%d/%Y")

```


```{r}

#===============================================================================
# Calculate place setting as integer values 
# (in this case age group rather than place)  
#===============================================================================

Pchart_Data$stateR <- rank(Pchart_Data$place, ties.method = "min")
Pchart_Data$StateRR <- match(Pchart_Data$stateR, sort(unique(Pchart_Data$stateR)))

Place_END <- max(Pchart_Data$StateRR)


#===============================================================================
# Work through each setting (age group) to calculate the limits 
# based on a P chart
#===============================================================================
OutputData = NULL

k=1
for (k in 1:Place_END) {
  
  Statei = 
    filter(Pchart_Data, StateRR == k) %>%
    compute_hybrid_p_chart()
  
  OutputData %<>% bind_rows(Statei)
  
} #k Setting Loop

```


```{r}

library(plotly)
plot_p_chart(
  data = OutputData %>% dplyr::filter(place == "12-14"))
  
```


```{r}
#-------------------------------------------------------------------------------
#   Create fields containing the Chart Title, and Sub-Title for use in
#   Google Studio
#-------------------------------------------------------------------------------

OutputData$Chart_Title <- paste(OutputData$place,": Daily Covid-19 Percent Positive Tests")

OutputData$Epoch_txt <- OutputData$EPOCH

OutputData$Sub_Title <- paste(OutputData$place, " is in Phase ", OutputData$Epoch_txt)


################################################################################
#
# Some very draft code to create the summary data table
# This needs work to correct and tidy up
#
################################################################################




Summ_Tab <- OutputData %>%
  group_by(place, EPOCH) %>%
  summarise(MIDLINEa = last(MIDLINEa), MIDLINEb = last(MIDLINEb), date = min(date) )


Summ_Tab2 <- Summ_Tab %>%
  group_by(place) %>%
  mutate(EPOCH_max = max(EPOCH)) %>%
  filter(EPOCH == EPOCH_max | EPOCH == EPOCH_max - 1)


Summ_Tab2[is.na(Summ_Tab2)] <- 0
Summ_Tab2$MIDLINE <- Summ_Tab2$MIDLINEa + Summ_Tab2$MIDLINEb

Summ_Tab3 <- Summ_Tab2 %>%
  group_by(place) %>%
  summarise(MIDLINE_0 = first(MIDLINE), date_0 = first(date), MIDLINE_1 = last(MIDLINE), date_1 = last(date) )


Summ_Tab3$datex <- ymd("2020-12-05")
Summ_Tab3$days <- Summ_Tab3$datex - Summ_Tab3$date_1
  

Summ_Tab3$Feedback <- "Blank"
Summ_Tab3$Feedback <- if_else(Summ_Tab3$days <= 7 & Summ_Tab3$MIDLINE_1 > Summ_Tab3$MIDLINE_0, 
                              paste("RED: Increased to ", round(100*Summ_Tab3$MIDLINE_1, 2), "%, ", Summ_Tab3$days, " days ago" ), 
                              Summ_Tab3$Feedback) 

Summ_Tab3$Feedback <- if_else(Summ_Tab3$days > 7 & Summ_Tab3$MIDLINE_1 > Summ_Tab3$MIDLINE_0, 
                              paste("GRAY: Has been at ", round(100*Summ_Tab3$MIDLINE_1, 2), "% for ", Summ_Tab3$days, " days" ), 
                              Summ_Tab3$Feedback) 

Summ_Tab3$Feedback <- if_else(Summ_Tab3$days <= 7 & Summ_Tab3$MIDLINE_1 <= Summ_Tab3$MIDLINE_0, 
                              paste("GREEN: Decreased to ", round(100*Summ_Tab3$MIDLINE_1, 2), "%, ", Summ_Tab3$days, " days ago" ), 
                              Summ_Tab3$Feedback) 

Summ_Tab3$Feedback <- if_else(Summ_Tab3$days > 7 & Summ_Tab3$MIDLINE_1 <= Summ_Tab3$MIDLINE_0, 
                              paste("GRAY: Has been at ", round(100*Summ_Tab3$MIDLINE_1, 2), "% for ", Summ_Tab3$days, " days" ), 
                              Summ_Tab3$Feedback) 


Summ_Tab3$Feedback <- paste("Since ", Summ_Tab3$date_1, " ", Summ_Tab3$place, " has percent positive cases varying around a mid line of ", round(Summ_Tab3$MIDLINE_1, 3) )

  

```

